version: "3" # composeファイルのバージョン
services: 
    front:
        build:
          context: ./front
        volumes:
          - ./front:/usr/src/app
        command: sh -c "yarn start"
        tty: true
        ports:
          - "3000:3000"
    api: # サービス名
        build: # ①ビルドに使うDockerfileの場所
            context: ./api
        command: /bin/sh -c "realize start"
        stdin_open: true
        tty: true # ②コンテナの永続化,コンテナは基本的に立ち上がって所定の処理が終わったら自動で閉じます。コンテナの永続化が必要な場合はtty:trueを入れてください。
        volumes:
            - ./api:/go/src/app # ③マウントディレクトリ
        ports: # ホストOSのポートとコンテナのポートをつなげる 
            - "8000:8080"
        depends_on:
            - "db"
    db:
      image: mysql:8.0
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: go_database
        MYSQL_USER: go_test
        MYSQL_PASSWORD: password
        TZ: 'Asia/Tokyo'
      command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      volumes:
        - db-data:/var/lib/mysql
        - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      ports:
        - 3306:3306
volumes:
  db-data:
    driver: local